SET NAMES latin1;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `_seed_send` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(26) default NULL,
  `ab` varchar(3) default NULL,
  `fips` varchar(9) default NULL,
  `ap` varchar(10) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=58 DEFAULT CHARSET=latin1;

insert into `_seed_send` values('1','Alabama','AL','01','Ala.'),
 ('2','Alaska','AK','02','Alaska'),
 ('3','Arizona','AZ','04','Ariz.'),
 ('4','Arkansas','AR','05','Ark.'),
 ('5','California','CA','06','Calif.'),
 ('6','Colorado','CO','08','Colo.'),
 ('7','Connecticut','CT','09','Conn.'),
 ('8','Delaware','DE','10','Del.'),
 ('9','District of Columbia','DC','11','D.C.'),
 ('10','Florida','FL','12','Fla.'),
 ('11','Georgia','GA','13','Ga.'),
 ('12','Hawaii','HI','15','Hawaii'),
 ('13','Idaho','ID','16','Idaho'),
 ('14','Illinois','IL','17','Ill.'),
 ('15','Indiana','IN','18','Ind.'),
 ('16','Iowa','IA','19','Iowa'),
 ('17','Kansas','KS','20','Kan.'),
 ('18','Kentucky','KY','21','Ky.'),
 ('19','Louisiana','LA','22','La.'),
 ('20','Maine','ME','23','Maine'),
 ('21','Maryland','MD','24','Md.'),
 ('22','Massachusetts','MA','25','Mass.'),
 ('23','Michigan','MI','26','Mich.'),
 ('24','Minnesota','MN','27','Minn.'),
 ('25','Mississippi','MS','28','Miss.'),
 ('26','Missouri','MO','29','Mo.'),
 ('27','Montana','MT','30','Mont.'),
 ('28','Nebraska','NE','31','Neb.'),
 ('29','Nevada','NV','32','Nev.'),
 ('30','New Hampshire','NH','33','N.H.'),
 ('31','New Jersey','NJ','34','N.J.'),
 ('32','New Mexico','NM','35','N.M.'),
 ('33','New York','NY','36','N.Y.'),
 ('34','North Carolina','NC','37','N.C.'),
 ('35','North Dakota','ND','38','N.D.'),
 ('36','Ohio','OH','39','Ohio'),
 ('37','Oklahoma','OK','40','Okla.'),
 ('38','Oregon','OR','41','Ore.'),
 ('39','Pennsylvania','PA','42','Pa.'),
 ('40','Rhode Island','RI','44','R.I.'),
 ('41','South Carolina','SC','45','S.C.'),
 ('42','South Dakota','SD','46','S.D.'),
 ('43','Tennessee','TN','47','Tenn.'),
 ('44','Texas','TX','48','Texas'),
 ('45','Utah','UT','49','Utah'),
 ('46','Vermont','VT','50','Vt.'),
 ('47','Virginia','VA','51','Va.'),
 ('48','Washington','WA','53','Wash.'),
 ('49','West Virginia','WV','54','W.Va.'),
 ('50','Wisconsin','WI','55','Wis.'),
 ('51','Wyoming','WY','56','Wyo.'),
 ('52','American Samoa','AS','60','Am. Samoa'),
 ('53','Guam','GU','66','Guam'),
 ('54','Northern Mariana Islands','MP','69','N. Mariana'),
 ('55','Puerto Rico','PR','72','P.R.'),
 ('57','Virgin Islands','VI','78','V.i.');

SET FOREIGN_KEY_CHECKS = 1;
